# yml文件与Properties文件都可以作为springboot的全局配置文件
# 如果两者同时存在，那么只有Properties文件配置的生效
server:
  port: 8081

person:
  lastName: zhangsan
  age: 18
  boss: false
  birth: 2017/12/12
  maps: {k1: v1,k2: 12}
  lists:
    - lisi
    - zhaoliu
  dog:
    name: 小狗
    age: 12



